import { Section, THEME } from "../../core/interfaces/system.interfaces";

export class Globals {
    static THEMES: THEME[] = [
        {
            NAME: "Blue (Default)",
            PRIMARY_COLOR: "#1F4E79",
            SECONDARY_COLOR: "#BDD7EE",
            ACCENT_COLOR: "#2E75B6",
            TEXT_COLOR: "#001E5B",
            SEPARATOR_COLOR: "#5999d4",
            MAIN_LINK_COLOR: "#0d6efd",
        },
        {
            NAME: "Green",
            PRIMARY_COLOR: "#1F7958",
            SECONDARY_COLOR: "#D7EEC5",
            ACCENT_COLOR: "#2EB676",
            TEXT_COLOR: "#005B1E",
            SEPARATOR_COLOR: "#59D45C",
            MAIN_LINK_COLOR: "#01d554",
        },
        {
            NAME: "Yellow",
            PRIMARY_COLOR: "#79791F",
            SECONDARY_COLOR: "#EEEEBD",
            ACCENT_COLOR: "#B6B62E",
            TEXT_COLOR: "#5B5B00",
            SEPARATOR_COLOR: "#D4D459",
            MAIN_LINK_COLOR: "#eaea05",
        },
        {
            NAME: "Orange",
            PRIMARY_COLOR: "#794E1F",
            SECONDARY_COLOR: "#EED7BD",
            ACCENT_COLOR: "#B6752E",
            TEXT_COLOR: "#5B1E00",
            SEPARATOR_COLOR: "#D45999",
            MAIN_LINK_COLOR: "#FD6E0D",
        },
        {
            NAME: "Brown",
            PRIMARY_COLOR: "#79421F",
            SECONDARY_COLOR: "#EED9BD",
            ACCENT_COLOR: "#B6572E",
            TEXT_COLOR: "#5B2900",
            SEPARATOR_COLOR: "#D48159",
            MAIN_LINK_COLOR: "#FD4D0D",
        },
        {
            NAME: "Purple",
            PRIMARY_COLOR: "#791F4E",
            SECONDARY_COLOR: "#EED7BD",
            ACCENT_COLOR: "#B62E75",
            TEXT_COLOR: "#5B001E",
            SEPARATOR_COLOR: "#D45999",
            MAIN_LINK_COLOR: "#FD0D6E",
        },
    ];

    static DEFAULTS = {
        THEME: Globals.THEMES[0],
        CONTACTS: {
            EMAIL: "",
            PHONE_NUMBERS: undefined,
            ADDRESS: "",
        },
        HEADER: {
            TITLE: "",
            INCLUDE_IMAGE: true,
            IMAGE: "",
        },
        CONFIGS: {
            MAIN_CONTENT_PADDING: 25,
            MAIN_CONTENT_PADDING_MIN: 10,
            MAIN_CONTENT_PADDING_MAX: 50,
            SIDEBAR_PADDING: 25,
            SIDEBAR_PADDING_MIN: 10,
            SIDEBAR_PADDING_MAX: 50,
            SIDEBAR_SPACE: 25,
            SIDEBAR_SPACE_MIN: 10,
            SIDEBAR_SPACE_MAX: 50,
            HEADER_FONT_SIZE: 30,
            HEADER_FONT_SIZE_MIN: 20,
            HEADER_FONT_SIZE_MAX: 50,
            IMAGE_WIDTH: 120,
            IMAGE_WIDTH_MIN: 120,
            IMAGE_WIDTH_MAX: 170,
            IMAGE_HEIGHT: 150,
            IMAGE_HEIGHT_MIN: 150,
            IMAGE_HEIGHT_MAX: 245,
            CONTACTS_FONT_SIZE: 15,
            CONTACTS_FONT_SIZE_MIN: 13,
            CONTACTS_FONT_SIZE_MAX: 20,
            CONTACTS_ICON_SIZE: 16,
            CONTACTS_ICON_SIZE_MIN: 14,
            CONTACTS_ICON_SIZE_MAX: 25,
            CONTACTS_SPACE: 10,
            CONTACTS_SPACE_MIN: 0,
            CONTACTS_SPACE_MAX: 20,
            CONTACTS_LIST_SPACE: 20,
            CONTACTS_LIST_SPACE_MIN: 10,
            CONTACTS_LIST_SPACE_MAX: 40,
            SECTION_TITLE_FONT_SIZE: 20,
            SECTION_TITLE_FONT_SIZE_MIN: 15,
            SECTION_TITLE_FONT_SIZE_MAX: 30,
            SECTION_TEXT_FONT_SIZE: 14,
            SECTION_TEXT_FONT_SIZE_MIN: 13,
            SECTION_TEXT_FONT_SIZE_MAX: 20,
            SECTION_SUB_TEXT_FONT_SIZE: 10,
            SECTION_SUB_TEXT_FONT_SIZE_MIN: 11,
            SECTION_SUB_TEXT_FONT_SIZE_MAX: 17,
            SECTION_TEXT_LINE_HEIGHT: 14,
            SECTION_TEXT_LINE_HEIGHT_MIN: 13,
            SECTION_TEXT_LINE_HEIGHT_MAX: 20,
            SECTION_SPACE: 16,
            SECTION_SPACE_MIN: 16,
            SECTION_SPACE_MAX: 30,
            SECTION_ITEM_SPACE: 5,
            SECTION_ITEM_SPACE_MIN: 0,
            SECTION_ITEM_SPACE_MAX: 10,
            SECTION_SEPARATOR_SPACE: 8,
            SECTION_SEPARATOR_SPACE_MIN: 2,
            SECTION_SEPARATOR_SPACE_MAX: 8,
            SECTION_LIST_ITEM_SPACE: 2,
            SECTION_LIST_ITEM_SPACE_MIN: 0,
            SECTION_LIST_ITEM_SPACE_MAX: 10,
        },
        SECTIONS: {
            SECTIONS: [] as Section[],
        },
        SIDEBAR: {
            SECTIONS: [] as Section[],
        },
    };
}
