import { Section } from "../../core/interfaces/system.interfaces";
import { ThemeStateModel } from "../../core/state/theme";

export class Globals {
    static THEMES: ThemeStateModel[] = [
        // {
        //     NAME: "Blue (Default)",
        //     PRIMARY_COLOR: "#1F4E79",
        //     SECONDARY_COLOR: "#BDD7EE",
        //     ACCENT_COLOR: "#2E75B6",
        //     TEXT_COLOR: "#001E5B",
        //     SEPARATOR_COLOR: "#5999d4",
        //     MAIN_LINK_COLOR: "#0d6efd",
        // },
        // {
        //     NAME: "Green",
        //     PRIMARY_COLOR: "#1F7958",
        //     SECONDARY_COLOR: "#D7EEC5",
        //     ACCENT_COLOR: "#2EB676",
        //     TEXT_COLOR: "#005B1E",
        //     SEPARATOR_COLOR: "#59D45C",
        //     MAIN_LINK_COLOR: "#01d554",
        // },
        // {
        //     NAME: "Yellow",
        //     PRIMARY_COLOR: "#79791F",
        //     SECONDARY_COLOR: "#EEEEBD",
        //     ACCENT_COLOR: "#B6B62E",
        //     TEXT_COLOR: "#5B5B00",
        //     SEPARATOR_COLOR: "#D4D459",
        //     MAIN_LINK_COLOR: "#eaea05",
        // },
        // {
        //     NAME: "Orange",
        //     PRIMARY_COLOR: "#794E1F",
        //     SECONDARY_COLOR: "#EED7BD",
        //     ACCENT_COLOR: "#B6752E",
        //     TEXT_COLOR: "#5B1E00",
        //     SEPARATOR_COLOR: "#D45999",
        //     MAIN_LINK_COLOR: "#FD6E0D",
        // },
        // {
        //     NAME: "Brown",
        //     PRIMARY_COLOR: "#79421F",
        //     SECONDARY_COLOR: "#EED9BD",
        //     ACCENT_COLOR: "#B6572E",
        //     TEXT_COLOR: "#5B2900",
        //     SEPARATOR_COLOR: "#D48159",
        //     MAIN_LINK_COLOR: "#FD4D0D",
        // },
        // {
        //     NAME: "Purple",
        //     PRIMARY_COLOR: "#791F4E",
        //     SECONDARY_COLOR: "#EED7BD",
        //     ACCENT_COLOR: "#B62E75",
        //     TEXT_COLOR: "#5B001E",
        //     SEPARATOR_COLOR: "#D45999",
        //     MAIN_LINK_COLOR: "#FD0D6E",
        // },
        //
        // {
        //     NAME: "Blue",
        //     PRIMARY_COLOR: "#1F4E79",
        //     SECONDARY_COLOR: "#BDD7EE",
        //     ACCENT_COLOR: "#2E75B6",
        //     TEXT_COLOR: "#001E5B",
        //     SEPARATOR_COLOR: "#5999D4",
        //     MAIN_LINK_COLOR: "#0D6EFD",
        // },
        // {
        //     NAME: "Green",
        //     PRIMARY_COLOR: "#167051",
        //     SECONDARY_COLOR: "#C8E6C9",
        //     ACCENT_COLOR: "#2E8B57",
        //     TEXT_COLOR: "#006400",
        //     SEPARATOR_COLOR: "#50C878",
        //     MAIN_LINK_COLOR: "#00FF00",
        // },
        // {
        //     NAME: "Red",
        //     PRIMARY_COLOR: "#731F1F",
        //     SECONDARY_COLOR: "#F5A9A9",
        //     ACCENT_COLOR: "#B22222",
        //     TEXT_COLOR: "#8B0000",
        //     SEPARATOR_COLOR: "#FF0000",
        //     MAIN_LINK_COLOR: "#FF6347",
        // },
        // {
        //     NAME: "Blue",
        //     PRIMARY_COLOR: "#1F4E79",
        //     SECONDARY_COLOR: "#BDD7EE",
        //     ACCENT_COLOR: "#2E75B6",
        //     TEXT_COLOR: "#001E5B",
        //     SEPARATOR_COLOR: "#5999D4",
        //     MAIN_LINK_COLOR: "#0D6EFD",
        // },
        // {
        //     NAME: "Green",
        //     PRIMARY_COLOR: "#167051",
        //     SECONDARY_COLOR: "#C8E6C9",
        //     ACCENT_COLOR: "#2E8B57",
        //     TEXT_COLOR: "#006400",
        //     SEPARATOR_COLOR: "#50C878",
        //     MAIN_LINK_COLOR: "#2E8B57",
        // },
        // {
        //     NAME: "Red",
        //     PRIMARY_COLOR: "#731F1F",
        //     SECONDARY_COLOR: "#F5A9A9",
        //     ACCENT_COLOR: "#B22222",
        //     TEXT_COLOR: "#8B0000",
        //     SEPARATOR_COLOR: "#FF0000",
        //     MAIN_LINK_COLOR: "#B22222",
        // },
        // {
        //     NAME: "Purple",
        //     PRIMARY_COLOR: "#4E2E4E",
        //     SECONDARY_COLOR: "#D8BFD8",
        //     ACCENT_COLOR: "#9400D3",
        //     TEXT_COLOR: "#4B0082",
        //     SEPARATOR_COLOR: "#BA55D3",
        //     MAIN_LINK_COLOR: "#9400D3",
        // },
        // {
        //     NAME: "Orange",
        //     PRIMARY_COLOR: "#CC6600",
        //     SECONDARY_COLOR: "#FFE5B4",
        //     ACCENT_COLOR: "#FFA500",
        //     TEXT_COLOR: "#FF7F00",
        //     SEPARATOR_COLOR: "#FFD700",
        //     MAIN_LINK_COLOR: "#FFA500",
        // },
        // {
        //     NAME: "Yellow",
        //     PRIMARY_COLOR: "#CCCC00",
        //     SECONDARY_COLOR: "#FFFFE0",
        //     ACCENT_COLOR: "#FFFF00",
        //     TEXT_COLOR: "#808000",
        //     SEPARATOR_COLOR: "#FFFFE0",
        //     MAIN_LINK_COLOR: "#FFFF00",
        // },
        // {
        //     NAME: "Pink",
        //     PRIMARY_COLOR: "#CC0066",
        //     SECONDARY_COLOR: "#FFB6C1",
        //     ACCENT_COLOR: "#FF69B4",
        //     TEXT_COLOR: "#8B008B",
        //     SEPARATOR_COLOR: "#FF1493",
        //     MAIN_LINK_COLOR: "#FF69B4",
        // },
        // {
        //     NAME: "Brown",
        //     PRIMARY_COLOR: "#996633",
        //     SECONDARY_COLOR: "#FFF8DC",
        //     ACCENT_COLOR: "#A52A2A",
        //     TEXT_COLOR: "#663300",
        //     SEPARATOR_COLOR: "#8B4513",
        //     MAIN_LINK_COLOR: "#A52A2A",
        // },
        // {
        //     NAME: "Teal",
        //     PRIMARY_COLOR: "#008080",
        //     SECONDARY_COLOR: "#E0FFFF",
        //     ACCENT_COLOR: "#00FFFF",
        //     TEXT_COLOR: "#003366",
        //     SEPARATOR_COLOR: "#AFEEEE",
        //     MAIN_LINK_COLOR: "#00FFFF",
        // },
        // {
        //     NAME: "Purple",
        //     PRIMARY_COLOR: "#6600CC",
        //     SECONDARY_COLOR: "#DCDCDC",
        //     ACCENT_COLOR: "#800080",
        //     TEXT_COLOR: "#4B0082",
        //     SEPARATOR_COLOR: "#BA55D3",
        //     MAIN_LINK_COLOR: "#800080",
        // },

        {
            name: "Sleek Blue",
            primaryColor: "#1F4E79",
            secondaryColor: "#BDD7EE",
            accentColor: "#0D6EFD",
            textColor: "#001E5B",
            separatorColor: "#5999D4",
            mainLinkColor: "#0D6EFD",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Ocean Blue",
            primaryColor: "#17a2b8",
            secondaryColor: "#BDD7EE",
            accentColor: "#007bff",
            textColor: "#000000",
            separatorColor: "#5999D4",
            mainLinkColor: "#007bff",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Vibrant Blue",
            primaryColor: "#17a2b8",
            secondaryColor: "#BDD7EE",
            accentColor: "#FDAE47",
            textColor: "#000000",
            separatorColor: "#5999D4",
            mainLinkColor: "#FDAE47",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Turquoise Blue",
            primaryColor: "#1ab394",
            secondaryColor: "#BDD7EE",
            accentColor: "#1C84C6",
            textColor: "#000000",
            separatorColor: "#5999D4",
            mainLinkColor: "#1C84C6",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Bright Green",
            primaryColor: "#18A64A",
            secondaryColor: "#A9F5D0",
            accentColor: "#18A64A",
            textColor: "#001E5B",
            separatorColor: "#A9F5D0",
            mainLinkColor: "#18A64A",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Classic Blue",
            primaryColor: "#1F4E79",
            secondaryColor: "#BDD7EE",
            accentColor: "#2E75B6",
            textColor: "#001E5B",
            separatorColor: "#5999D4",
            mainLinkColor: "#2E75B6",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Dark Burgundy",
            primaryColor: "#8E2323",
            secondaryColor: "#FFC8C8",
            accentColor: "#D90429",
            textColor: "#001E5B",
            separatorColor: "#FFC8C8",
            mainLinkColor: "#D90429",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Gentle Peach",
            primaryColor: "#FFE5B4",
            secondaryColor: "#FFB347",
            accentColor: "#FFB347",
            textColor: "#001E5B",
            separatorColor: "#FFB347",
            mainLinkColor: "#FFB347",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Deep Purple",
            primaryColor: "#7D26CD",
            secondaryColor: "#D9B3FF",
            accentColor: "#7D26CD",
            textColor: "#001E5B",
            separatorColor: "#D9B3FF",
            mainLinkColor: "#7D26CD",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Teal",
            primaryColor: "#008080",
            secondaryColor: "#B2DFDB",
            accentColor: "#009688",
            textColor: "#004C4C",
            separatorColor: "#4DB6AC",
            mainLinkColor: "#00BFA5",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Navy",
            primaryColor: "#001F3F",
            secondaryColor: "#ADD8E6",
            accentColor: "#000080",
            textColor: "#00001C",
            separatorColor: "#5F9EA0",
            mainLinkColor: "#0000FF",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Maroon",
            primaryColor: "#800000",
            secondaryColor: "#FFE4E1",
            accentColor: "#8B0000",
            textColor: "#4C0000",
            separatorColor: "#A52A2A",
            mainLinkColor: "#FF0000",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Green",
            primaryColor: "#3CB371",
            secondaryColor: "#90EE90",
            accentColor: "#006400",
            textColor: "#003300",
            separatorColor: "#2E8B57",
            mainLinkColor: "#008000",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Purple",
            primaryColor: "#800080",
            secondaryColor: "#E6E6FA",
            accentColor: "#663399",
            textColor: "#330033",
            separatorColor: "#9370DB",
            mainLinkColor: "#FF00FF",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Mint Green",
            primaryColor: "#229954",
            secondaryColor: "#A2D9CE",
            accentColor: "#48C9B0",
            textColor: "#006600",
            separatorColor: "#1ABC9C",
            mainLinkColor: "#48C9B0",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Deep Purple",
            primaryColor: "#663399",
            secondaryColor: "#D7BDE2",
            accentColor: "#9B59B6",
            textColor: "#240066",
            separatorColor: "#8E44AD",
            mainLinkColor: "#9B59B6",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Bright Orange",
            primaryColor: "#FF5733",
            secondaryColor: "#FFE5CC",
            accentColor: "#FFC300",
            textColor: "#663300",
            separatorColor: "#FFA07A",
            mainLinkColor: "#FFC300",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Steel Gray",
            primaryColor: "#708090",
            secondaryColor: "#C7CCD1",
            accentColor: "#C0C0C0",
            textColor: "#333",
            separatorColor: "#BFBFBF",
            mainLinkColor: "#C0C0C0",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Sapphire Blue",
            primaryColor: "#0F52BA",
            secondaryColor: "#BFD8EE",
            accentColor: "#0077C9",
            textColor: "#003366",
            separatorColor: "#5499C7",
            mainLinkColor: "#0077C9",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Vibrant Blue",
            primaryColor: "#1F4E79",
            secondaryColor: "#BDD7EE",
            accentColor: "#2E75B6",
            textColor: "#001E5B",
            separatorColor: "#5999D4",
            mainLinkColor: "#2E75B6",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Electric Purple",
            primaryColor: "#4B0082",
            secondaryColor: "#D6D6D6",
            accentColor: "#9400D3",
            textColor: "#3F3F3F",
            separatorColor: "#7B68EE",
            mainLinkColor: "#9400D3",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Fiery Red",
            primaryColor: "#800000",
            secondaryColor: "#F5F5DC",
            accentColor: "#FF4500",
            textColor: "#3F3F3F",
            separatorColor: "#B22222",
            mainLinkColor: "#FF4500",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Sunny Yellow",
            primaryColor: "#FFD700",
            secondaryColor: "#FFFFE0",
            accentColor: "#FFFF00",
            textColor: "#3F3F3F",
            separatorColor: "#EEE8AA",
            mainLinkColor: "#FFFF00",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Forest Green",
            primaryColor: "#228B22",
            secondaryColor: "#90EE90",
            accentColor: "#32CD32",
            textColor: "#3F3F3F",
            separatorColor: "#98FB98",
            mainLinkColor: "#32CD32",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Tropical Teal",
            primaryColor: "#1F9D71",
            secondaryColor: "#B5EAD7",
            accentColor: "#3EBE9E",
            textColor: "#005C4F",
            separatorColor: "#5ED5A5",
            mainLinkColor: "#3EBE9E",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Royal Purple",
            primaryColor: "#800080",
            secondaryColor: "#E6E6FA",
            accentColor: "#9370DB",
            textColor: "#3F3F3F",
            separatorColor: "#DDA0DD",
            mainLinkColor: "#9370DB",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Sunset Orange",
            primaryColor: "#FF5733",
            secondaryColor: "#FFD6B3",
            accentColor: "#FF7C4D",
            textColor: "#663500",
            separatorColor: "#FFA347",
            mainLinkColor: "#FF7C4D",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Majestic Purple",
            primaryColor: "#7B3F8D",
            secondaryColor: "#D3C3F2",
            accentColor: "#966FD6",
            textColor: "#410066",
            separatorColor: "#A78DF2",
            mainLinkColor: "#966FD6",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Vibrant Red",
            primaryColor: "#D60A0A",
            secondaryColor: "#F2C3C3",
            accentColor: "#FF0D0D",
            textColor: "#660000",
            separatorColor: "#F25A5A",
            mainLinkColor: "#FF0D0D",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Ocean Blue",
            primaryColor: "#0D6EFD",
            secondaryColor: "#BDD7EE",
            accentColor: "#1F87D9",
            textColor: "#001E5B",
            separatorColor: "#5999D4",
            mainLinkColor: "#1F87D9",
            backgroundColor: "#FFFFFF",
        },
        {
            name: "Midnight Black",
            primaryColor: "#0E2E40",
            secondaryColor: "#1B1E2D",
            accentColor: "#3F7CAC",
            textColor: "#F9F9F9",
            separatorColor: "#3F7CAC",
            mainLinkColor: "#3F7CAC",
            backgroundColor: "#3A3A3A",
        },
        {
            name: "Dark Maroon",
            primaryColor: "#7f1d1d",
            secondaryColor: "#2b0e0e",
            accentColor: "#d13b3b",
            textColor: "#f9f9f9",
            separatorColor: "#cc5c5c",
            mainLinkColor: "#f9f9f9",
            backgroundColor: "#1d1d1d",
        },
        {
            name: "Deep Purple",
            primaryColor: "#4b0082",
            secondaryColor: "#1d1d1d",
            accentColor: "#9a32cd",
            textColor: "#f9f9f9",
            separatorColor: "#7a5bcc",
            mainLinkColor: "#f9f9f9",
            backgroundColor: "#1d1d1d",
        },
        {
            name: "Mystical Black",
            primaryColor: "#0f0f0f",
            secondaryColor: "#1d1d1d",
            accentColor: "#5b5b5b",
            textColor: "#f9f9f9",
            separatorColor: "#2b2b2b",
            mainLinkColor: "#f9f9f9",
            backgroundColor: "#1d1d1d",
        },
        {
            name: "Dark Sapphire",
            primaryColor: "#0f0f5b",
            secondaryColor: "#1d1d7a",
            accentColor: "#3b3bd1",
            textColor: "#f9f9f9",
            separatorColor: "#5b5bcc",
            mainLinkColor: "#f9f9f9",
            backgroundColor: "#1d1d1d",
        },
        {
            name: "Midnight Navy",
            primaryColor: "#00005b",
            secondaryColor: "#1d1d7a",
            accentColor: "#3b3bbb",
            textColor: "#f9f9f9",
            separatorColor: "#5b5b99",
            mainLinkColor: "#f9f9f9",
            backgroundColor: "#1d1d1d",
        },
        {
            name: "Dark Ocean",
            primaryColor: "#053C5C",
            secondaryColor: "#0B3E3E",
            accentColor: "#0B8080",
            textColor: "#F9F9F9",
            separatorColor: "#1F9D71",
            mainLinkColor: "#0B8080",
            backgroundColor: "#0B3E3E",
        },
        {
            name: "Midnight Purple",
            primaryColor: "#360033",
            secondaryColor: "#1A003D",
            accentColor: "#5D0072",
            textColor: "#F9F9F9",
            separatorColor: "#1F9D71",
            mainLinkColor: "#5D0072",
            backgroundColor: "#1A003D",
        },
        {
            name: "Elegant Black",
            primaryColor: "#000000",
            secondaryColor: "#1A1A1A",
            accentColor: "#808080",
            textColor: "#F9F9F9",
            separatorColor: "#1F9D71",
            mainLinkColor: "#808080",
            backgroundColor: "#1A1A1A",
        },
        {
            name: "Gothic Grey",
            primaryColor: "#383838",
            secondaryColor: "#2E2E2E",
            accentColor: "#6E6E6E",
            textColor: "#F9F9F9",
            separatorColor: "#1F9D71",
            mainLinkColor: "#6E6E6E",
            backgroundColor: "#2E2E2E",
        },
        {
            name: "Mysterious Dark",
            primaryColor: "#0B3E3E",
            secondaryColor: "#053C5C",
            accentColor: "#0B8080",
            textColor: "#F9F9F9",
            separatorColor: "#1F9D71",
            mainLinkColor: "#0B8080",
            backgroundColor: "#053C5C",
        },
        {
            name: "Mystical Black",
            primaryColor: "#0E0E0E",
            secondaryColor: "#1C1C1C",
            accentColor: "#686868",
            textColor: "#F9F9F9",
            separatorColor: "#484848",
            mainLinkColor: "#686868",
            backgroundColor: "#232323",
        },
        {
            name: "Midnight Blue",
            primaryColor: "#0E0E3F",
            secondaryColor: "#1C1C5E",
            accentColor: "#6868B8",
            textColor: "#F9F9F9",
            separatorColor: "#4848A0",
            mainLinkColor: "#6868B8",
            backgroundColor: "#232359",
        },
        {
            name: "Midnight Blue Darker",
            primaryColor: "#1c2331",
            secondaryColor: "#0d0d1a",
            accentColor: "#0652DD",
            textColor: "#FFFFFF",
            separatorColor: "#5999D4",
            mainLinkColor: "#0652DD",
            backgroundColor: "#0C1E3F",
        },
        {
            name: "Dark Forest",
            primaryColor: "#0E3F0E",
            secondaryColor: "#042104",
            accentColor: "#68B868",
            textColor: "#F9F9F9",
            separatorColor: "#48A048",
            mainLinkColor: "#68B868",
            backgroundColor: "#235E23",
        },
        {
            name: "Charcoal Gray",
            primaryColor: "#3F3F3F",
            secondaryColor: "#4c4c4c",
            accentColor: "#B8B8B8",
            textColor: "#F9F9F9",
            separatorColor: "#A0A0A0",
            mainLinkColor: "#B8B8B8",
            backgroundColor: "#5E5E5E",
        },
        {
            name: "Shadowy Black",
            primaryColor: "#0F0F0F",
            secondaryColor: "#1E1E1E",
            accentColor: "#696969",
            textColor: "#F9F9F9",
            separatorColor: "#494949",
            mainLinkColor: "#696969",
            backgroundColor: "#222222",
        },
        {
            name: "Mysterious Black",
            primaryColor: "#2F2E41",
            secondaryColor: "#17181E",
            accentColor: "#C1C1CC",
            textColor: "#F9F9F9",
            separatorColor: "#3C3B4D",
            mainLinkColor: "#7D7D86",
            backgroundColor: "#0D0D0D",
        },
        {
            name: "Midnight Gray",
            primaryColor: "#2F2E41",
            secondaryColor: "#3C3B4D",
            accentColor: "#C1C1CC",
            textColor: "#F9F9F9",
            separatorColor: "#17181E",
            mainLinkColor: "#7D7D86",
            backgroundColor: "#121212",
        },
        {
            name: "Dark Knight",
            primaryColor: "#17181E",
            secondaryColor: "#3C3B4D",
            accentColor: "#C1C1CC",
            textColor: "#F9F9F9",
            separatorColor: "#2F2E41",
            mainLinkColor: "#7D7D86",
            backgroundColor: "#0D0D0D",
        },
    ];

    static DEFAULTS = {
        theme: Globals.THEMES[0],
        header: {
            name: "",
            title: "",
            includeImage: true,
            image: "",
        },
        contacts: {
            email: "",
            phoneNumbers: undefined,
            address: "",
            refereesUponRequest: undefined,
        },
        configs: {
            dynamics: {},
            mainContentPadding: 25,
            mainContentPaddingMin: 0,
            mainContentPaddingMax: 500,
            sidebarPadding: 25,
            sidebarPaddingMin: 0,
            sidebarPaddingMax: 500,
            sidebarSpace: 25,
            sidebarSpaceMin: 0,
            sidebarSpaceMax: 500,
            headerNameFontSize: 30,
            headerNameFontSizeMin: 0,
            headerNameFontSizeMax: 500,
            headerNameLineHeight: 30,
            headerNameLineHeightMin: 0,
            headerNameLineHeightMax: 500,
            headerTitleFontSize: 20,
            headerTitleFontSizeMin: 0,
            headerTitleFontSizeMax: 500,
            headerTitleLineHeight: 20,
            headerTitleLineHeightMin: 0,
            headerTitleLineHeightMax: 500,
            imageWidth: 120,
            imageWidthMin: 0,
            imageWidthMax: 500,
            imageHeight: 150,
            imageHeightMin: 0,
            imageHeightMax: 500,
            contactsFontSize: 15,
            contactsFontSizeMin: 0,
            contactsFontSizeMax: 500,
            contactsIconSize: 16,
            contactsIconSizeMin: 0,
            contactsIconSizeMax: 500,
            contactsSpace: 10,
            contactsSpaceMin: 0,
            contactsSpaceMax: 500,
            contactsListSpace: 20,
            contactsListSpaceMin: 0,
            contactsListSpaceMax: 500,
            sectionTitleFontSize: 20,
            sectionTitleFontSizeMin: 0,
            sectionTitleFontSizeMax: 500,
            sectionTextFontSize: 14,
            sectionTextFontSizeMin: 0,
            sectionTextFontSizeMax: 500,
            sectionSubTextFontSize: 10,
            sectionSubTextFontSizeMin: 0,
            sectionSubTextFontSizeMax: 500,
            sectionTextLineHeight: 14,
            sectionTextLineHeightMin: 0,
            sectionTextLineHeightMax: 500,
            sectionSpace: 16,
            sectionSpaceMin: 0,
            sectionSpaceMax: 500,
            sectionItemSpace: 5,
            sectionItemSpaceMin: 0,
            sectionItemSpaceMax: 500,
            sectionSeparatorSpace: 8,
            sectionSeparatorSpaceMin: 0,
            sectionSeparatorSpaceMax: 500,
            sectionListItemSpace: 2,
            sectionListItemSpaceMin: 0,
            sectionListItemSpaceMax: 500,
        },
        // configs: {
        //     dynamics: {},
        //     mainContentPadding: 25,
        //     mainContentPaddingMin: 10,
        //     mainContentPaddingMax: 50,
        //     sidebarPadding: 25,
        //     sidebarPaddingMin: 10,
        //     sidebarPaddingMax: 50,
        //     sidebarSpace: 25,
        //     sidebarSpaceMin: 10,
        //     sidebarSpaceMax: 50,
        //     headerNameFontSize: 30,
        //     headerNameFontSizeMin: 20,
        //     headerNameFontSizeMax: 50,
        //     headerNameLineHeight: 30,
        //     headerNameLineHeightMin: 20,
        //     headerNameLineHeightMax: 50,
        //     headerTitleFontSize: 20,
        //     headerTitleFontSizeMin: 13,
        //     headerTitleFontSizeMax: 25,
        //     headerTitleLineHeight: 20,
        //     headerTitleLineHeightMin: 13,
        //     headerTitleLineHeightMax: 25,
        //     imageWidth: 120,
        //     imageWidthMin: 120,
        //     imageWidthMax: 170,
        //     imageHeight: 150,
        //     imageHeightMin: 150,
        //     imageHeightMax: 245,
        //     contactsFontSize: 15,
        //     contactsFontSizeMin: 13,
        //     contactsFontSizeMax: 20,
        //     contactsIconSize: 16,
        //     contactsIconSizeMin: 14,
        //     contactsIconSizeMax: 25,
        //     contactsSpace: 10,
        //     contactsSpaceMin: 0,
        //     contactsSpaceMax: 20,
        //     contactsListSpace: 20,
        //     contactsListSpaceMin: 10,
        //     contactsListSpaceMax: 40,
        //     sectionTitleFontSize: 20,
        //     sectionTitleFontSizeMin: 15,
        //     sectionTitleFontSizeMax: 30,
        //     sectionTextFontSize: 14,
        //     sectionTextFontSizeMin: 13,
        //     sectionTextFontSizeMax: 20,
        //     sectionSubTextFontSize: 10,
        //     sectionSubTextFontSizeMin: 11,
        //     sectionSubTextFontSizeMax: 17,
        //     sectionTextLineHeight: 14,
        //     sectionTextLineHeightMin: 13,
        //     sectionTextLineHeightMax: 20,
        //     sectionSpace: 16,
        //     sectionSpaceMin: 16,
        //     sectionSpaceMax: 30,
        //     sectionItemSpace: 5,
        //     sectionItemSpaceMin: 0,
        //     sectionItemSpaceMax: 10,
        //     sectionSeparatorSpace: 8,
        //     sectionSeparatorSpaceMin: 2,
        //     sectionSeparatorSpaceMax: 8,
        //     sectionListItemSpace: 2,
        //     sectionListItemSpaceMin: 0,
        //     sectionListItemSpaceMax: 10,
        // },
        sections: {
            sections: [] as Section[],
        },
        sidebar: {
            sections: [] as Section[],
        },
    };
}
